# Generated by Django 5.0.2 on 2024-02-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_remove_receita_ingredientes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='author',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='title',
            new_name='password',
        ),
    ]
