# Generated by Django 5.0.2 on 2024-03-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
