# Generated by Django 5.0.2 on 2024-03-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='login',
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
