# Generated by Django 5.0.2 on 2024-03-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='confirm_password',
            new_name='confirmPassword',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='user_name',
            new_name='username',
        ),
    ]
