# Generated by Django 5.0.2 on 2024-03-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipes_intensidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='intensidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
