# Generated by Django 5.0.2 on 2024-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipes_user_ingredient_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='user_id',
        ),
        migrations.AddField(
            model_name='recipes',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
