# Generated by Django 5.0.2 on 2024-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_ingredient_user_id_recipes_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
